<script>
    require(["jquery", 'underscore', 'Magento_Ui/js/modal/modal'], function ($) {
        $(document).ready(function() {

            var parentBody = window.parent.document.body;
            $('.mfp-preloader', parentBody).css('display', 'none');
            $('.mfp-close', parentBody).css('display', 'block');

            $('.mfp-iframe-holder .mfp-content', parentBody).css('width', '100%');
            $('.mfp-iframe-holder .mfp-content', parentBody).css('height', '100%');
            $('.mfp-iframe-holder', parentBody).addClass('fadeInFromLeft');
            $('.mfp-iframe-scaler iframe', parentBody).css({'opacity': 1});
            $('body').addClass('weltpixel-quickview-slideIn');


            $('.reviews-actions a').attr('target', '_parent');
            $('.product-social-links a').attr('target', '_parent');

        });
    });
</script>