<div class="w footer-v3">
    <div class="footer-section2-content row">

        <div class="col-md-12 footer-links-section">
            <div class="row footer-links">
                <div class="mobile-toggle address-v3">
                    <div class="mini-logo">
                        <img alt="Logo" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl().'wysiwyg/pearl_theme/logo.png' ?>">
                    </div>
                    <div class="details-v3">
                        <div class="store-time">
                            <strong>
                                <p>Working Hours</p>
                            </strong>
                            <p>10:30 AM - 8:30 PM</p>
                            <p> Monday to Sunday</p>
                        </div>
                    </div>
                </div>


                <div class="mobile-toggle">
                    <h4 class="no-padding-mob">About Us</h4>
                    <ul class="footer-v3-list">
                        <li><a href="http://pmjjewels.com/">Legacy</a></li>
                        <li><a href="http://pmjjewels.com/#diamond">Diamond Quality</a></li>
                        <li><a href="http://pmjjewels.com/#design">Designs</a></li>
                        <li><a href="<?php echo $this->getUrl('privacy'); ?>">Privacy</a></li>
                        <li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms of Use</a></li>
                        <li><a href="https://www.pmjjewels.com/pmjworld">PMJ World</a></li>
                        <!-- <li><a target="_blank" href="<?php echo $this->getUrl('blog'); ?>" title="Contact">Blog</a></li> -->
                        <!-- <li><a target="_blank" href="<?php echo $this->getUrl('sales/guest/form/'); ?>" title="Contact">Track Order</a></li> -->
                    </ul>
                </div>

                <div class="mobile-toggle">
                    <h4 class="no-padding-mob">Quick Links</h4>
                    <ul class="footer-v3-list">
                        <li><a href="<?php echo $this->getUrl('site-map'); ?>" title="Site Map">Site Map</a></li>
                        <!-- <li><a href="<?php echo $this->getUrl('store-locator'); ?>" title="Store Locator">Store Locator</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('video-store'); ?>" title="Video Store">Video Store</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('fast-delivery'); ?>" title="Fast Delivery">Fast Delivery</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('pmj-benefits'); ?>" title="PMJ Benefits">PMJ Benefits</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('return-policy'); ?>" title="Return Policy">Return Policy</a></li> -->
                        <!-- <li><a href="<?php echo $block->getViewFileUrl('Codilar_SizeGuide::ring_size_guide.jpg'); ?>"
                                target="_blank" title="Ring Size">Ring Size</a></li>
                        <li><a href="<?php echo $block->getViewFileUrl('Codilar_SizeGuide::ring_size_guide.jpg'); ?>"
                                target="_blank" title="Bangle Size">Bangle Size</a></li>
                        <li><a href="<?php echo $this->getUrl('customer-testimonials'); ?>" title="Customer Testimonial">Customer
                                Testimonial</a></li> -->
                    </ul>
                </div>
                <div class="mobile-toggle">
                    <h4 class="no-padding-mob">Customer Service</h4>
                    <ul class="footer-v3-list">
                        <li><a href="<?php echo $this->getUrl('contact'); ?>" title="Contact">Contact Us</a></li>
                        <li><a href="<?php echo $this->getUrl('store-locator'); ?>" title="Store Locator">Store Locator</a></li>
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service'); ?>" title="Customer Service">Customer Service</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service/lifetime-warranty'); ?>" title="Lifetime warranty">Lifetime warranty</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service/free-shipping'); ?>" title="Free Shipping">Free Shipping</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service/hassle-free-returns'); ?>" title="Hassle free returns">Hassle free returns</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service/free-engraving'); ?>" title="Free Engraving">Free Engraving</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service/free-resizings'); ?>" title="Free resizings">Free resizings</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('customer-service/lifetime-upgrade'); ?>" title="Lifetime upgrade">Lifetime upgrade</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('payment-options'); ?>" title="Payment Options">Payment Options</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('faq'); ?>" title="FAQ">FAQ</a></li> -->
                        <!-- <li><a href="<?php echo $this->getUrl('education'); ?>" title="Education">Education</a></li> -->
                    </ul>
                </div>
                <div class="mobile-toggle contact-main-box">
                    <h4 class="no-padding-mob">Get in Touch</h4>
                    <div class="contact-details-main">
                    <!-- <div class="number">
                        <i class="icon icon-call"></i>
                        <a href="tel:8008019281">+91 800 801 9281</a>
                    </div> -->
                    <div class="whatsapp-number">
                        <img class="whatsapp-img" src="<?= $block->getViewFileUrl('images/whatsapp-logo.png'); ?>"
                            alt="">
                        <a class="only-desktop" href="https://web.whatsapp.com/send?phone=918008019281&amp;text=Hello PMJ Jewels. I am interested in your PMJ Jewels services." target="_blank">+91 800 801 9281</a>
                        <a class="only-mobile" href="https://api.whatsapp.com/send?phone=918008019281&amp;text=Hello PMJ Jewels. I am interested in your PMJ Jewels services." target="_blank">+91 800 801 9281</a>
                    </div>
                    <div class="newsletter-title">
                        <h4 class="no-padding-mob">Let's Stay in touch!</h4>
                    </div>
                    <div class="social-icons-main">
                        <a href="https://www.facebook.com/PMJJewels/" class="social-icon-item">
                            <i class="icon-facebook"></i>
                        </a>
                        <a href="https://twitter.com/PMJJewels1964" class="social-icon-item">
                            <i class="icon-twitter"></i>
                        </a>
                        <a href="https://www.instagram.com/pmj_jewels/" class="social-icon-item">
                            <i class="icon-instagram"></i>
                        </a>
                    </div>
                    <div class="payment-options">
                        <h4 class="no-padding-mob">Payment Options</h4>
                        <div class="img-main">
                            <img src="<?= $block->getViewFileUrl('images/mastercard.svg'); ?>" alt="">
                            <img src="<?= $block->getViewFileUrl('images/visa.svg'); ?>" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $('body').click(function (e) {
            if (e.target.className == 'cart-button-text') {
                $('#videocart-dropdown').toggle();
            } else {
                $('#videocart-dropdown').hide();
            }
        });
    });
</script>