<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$session = $objectManager->create('Magento\Catalog\Model\Session');
$keySession = $block->getKeySession();
$_url = $objectManager->create('Magento\Framework\UrlInterface'); 
$ajaxUrl = $_url->getUrl('/category/thumb').'keys/'.$keySession;
?>
<script>
	require([
		'jquery',
		'mage/adminhtml/grid',
		'prototype'], 
		function (jQuery) {
			jQuery("#edit_form").append('<input type="hidden" id="item_thumb_id" name="item_thumb_id" value="<?php echo $block->getItemThumbId() ?>">');
			jQuery('body').append('<div data-role="loader" class="loading-mask-gallery" style="display: none;"><div class="popup popup-loading"><div class="popup-inner">Please wait...</div></div></div>');
			jQuery(document).ready(function () {
				jQuery('#edit_form ').on('click', 'table tbody tr td input:radio', function (){
					jQuery('.loading-mask-gallery').show();
					id = jQuery(this).val();
					url = '<?php echo $ajaxUrl ?>';
					jQuery.ajax({
						url: url,
						type: "POST",
						data: "id="+id,
						success: function(data) {
							console.log('<?php echo $session->getKeySession() ?>');
							jQuery('.loading-mask-gallery').hide();
							jQuery('input[name="item_thumb_id"]').val(id);
						}
					});
				});
			});
		}
		);
	</script>


