<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
// foreach ($_productCollection as $product) {
//     echo "<pre>";
//     $a = $product->getData();     
//     echo "<br>";
// }die;
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <?php $placeholderImage = $block->getImage($_product, 'category_page_grid')->getImageUrl();
            ?>

            <li class="item product product-item col-xs-12 col-sm-12 col-md-6-custom p-0">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    // $productImage = $block->getImage($_product, $imageDisplayArea);
                    // if ($pos != null) {
                    //     $position = ' style="left:' . $productImage->getWidth() . 'px;'
                    //         . 'top:' . $productImage->getHeight() . 'px;"';
                    // }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php //$productImage->toHtml(); ?>
                        <?php $customImages = explode(',',$_product['image_custom_urls']);
                            $emptyCheckIurl = (!empty(array_filter($customImages)))? 1:0;
                            $videoUrl = explode(',',$_product['video_thumbnail_url']);
                            $emptyCheckVurl = (!empty(array_filter($videoUrl)))? 1:0;
                        ?>
                        <span class="product-image-container" style="width:560px;">
                        <span class="product-image-wrapper" style="padding-bottom: 71.428571428571%;">
                            <?php if($emptyCheckIurl) {?>  
                            <img class="product-image-photo" src="<?php echo $customImages[0] ?>" max-width="560" max-height="400" alt="<?php $_product['name'] ?>">
                            <?php } elseif($emptyCheckVurl){?>
                                <img class="product-image-photo" src="<?php echo $videoUrl[0] ?>" max-width="560" max-height="400" alt="<?php $_product['name'] ?>">
                            <?php } else{?>
                        <img class="product-image-photo" src="<?php echo $placeholderImage ?>" max-width="560" max-height="400" alt="<?php $_product['name'] ?>">
    
                            <?php }?>
                         
                        </span>
                        </span>
                    </a>
                    <div class="product details product-item-details text-center">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name d-flex justify-content-center">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getStockCode(), 'stock_code') ?>
                            </a>
                            <input type="checkbox" title="Add video" class="video-list-checkbox ml-2" id="<?php echo $_product->getId(); ?>" name="video-checkbox" value="<?php echo $_product->getId(); ?>"/>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner d-none">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="d-none actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary d-none"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    requirejs(['jquery','mage/url'], function (jQuery,murl) {

         jQuery(document).ready(function(){

            var checkboxValues = JSON.parse(localStorage.getItem('checkboxValues')) || {},
            checkboxes = jQuery(".product-item-info :checkbox");

            jQuery('.video-list-checkbox').change(function() {

                 jQuery(checkboxes).each(function(){
                    console.log('testing',this.checked);
                    checkboxValues[this.id] = this.checked;
                 });


                 localStorage.setItem("checkboxValues", JSON.stringify(checkboxValues));

                if(jQuery(this).is(":checked")) {
                       var id = jQuery(this).val();
                        jQuery.ajax({
                            type: "post",
                            url: murl.build('videostore/cart/addnew'),
                            data:{
                                'product-id': id,
                            },
                            success: function (data, status) {
                            }
                        });
                    }

                });

                // On page load
                    jQuery.each(checkboxValues, function(key, value) {
                      jQuery("#" + key).prop('checked', value);
                    });
             });
        });
</script>


