<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $pageBlock \Codilar\Rapnet\Block\RapnetProducts $rapnetProductsBlock */
$rapnetProductsBlock = $block->getLayout()->createBlock('Codilar\Rapnet\Block\RapnetProducts');
$currentProduct = $rapnetProductsBlock->getCurrentProduct();
$helperProductPage = $this->helper('WeltPixel\ProductPage\Helper\Data');
$accordionVersion = $helperProductPage->getAccordionVersion($helperProductPage->getStoreId());
$accordionCollapsible = $helperProductPage->isAccordionCollapsible($helperProductPage->getStoreId());
$noBorder = '';
$noBorderAccordion = '';


?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')) : ?>
    <?php if ($helperProductPage->getTabsLayout() == 'accordion')  : ?>
        <?php
        // Check if accordion version is Version 2
        if ($accordionVersion == '1'): ?>
            <div class="product info detailed">
                <?php $layout = $block->getLayout(); ?>
                <div class="product data items acc-v2-noborder"
                     data-mage-init='{"tabs":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true, "animate": 300}}'>
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <div class="bg-accordion"
                             aria-labeledby="tab-label-<?= /* @escapeNotVerified */
                             $alias ?>-title"
                             data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
                        $alias ?>">
                            <a class="bg-link"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?= /* @escapeNotVerified */
                               $alias ?>"
                               id="tab-label-<?= /* @escapeNotVerified */
                               $alias ?>-title" data-role="trigger">
                                <?= /* @escapzeNotVerified */
                                $label ?>
                            </a>
                        </div>
                        <div class="cnt-acc" id="<?= /* @escapeNotVerified */
                        $alias ?>" data-role="content">
                            <div class="content-acc">
                                <?= /* @escapeNotVerified */
                                $html ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php else: ?>
            <?php $noBorderAccordion = $helperProductPage->getAccordionVersion() == '0' ? 'no-border-accordion' : '' ?>
            <div class="product-info-main-extend">
                <div class="accordion-1 product info detailed <?php echo $noBorder; ?>">
                    <?php $layout = $block->getLayout(); ?>
                    <div class="product data items"
                         data-mage-init='{"tabs":{"openedState":"active" <?php echo $accordionCollapsible ? ', "collapsible": "true"' : ''; ?>  }}'>
                        <?php foreach ($detailedInfoGroup as $name): ?>
                            <?php
                            $html = $layout->renderElement($name);
                            if (!trim($html)) {
                                continue;
                            }
                            $alias = $layout->getElementAlias($name);
                            $label = $block->getChildData($alias, 'title');
                            ?>
                            <div class="data item title <?php echo $noBorderAccordion; ?>"
                                 aria-labeledby="tab-label-<?= /* @escapeNotVerified */
                                 $alias ?>-title"
                                 data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
                            $alias ?>">
                                <a class="data switch <?php echo $noBorderAccordion; ?>"
                                   tabindex="-1"
                                   data-toggle="switch"
                                   href="#<?= /* @escapeNotVerified */
                                   $alias ?>"
                                   id="tab-label-<?= /* @escapeNotVerified */
                                   $alias ?>-title">
                                    <?= /* @escapeNotVerified */
                                    $label ?>
                                </a>
                            </div>
                            <div class="data item content <?php echo $noBorderAccordion; ?>"
                                 id="<?= /* @escapeNotVerified */
                                 $alias ?>" data-role="content">
                                <?= /* @escapeNotVerified */
                                $html ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    <?php else: ?>
        <?php $noBorder = $helperProductPage->getTabsLayout() == 'tab' && $helperProductPage->getTabsVersion() == '1' ? 'no-border' : '' ?>
        <div class="tabs-1 product info detailed <?php echo $noBorder; ?>">
            <?php $layout = $block->getLayout(); ?>

            <?php if ($currentProduct->getAttributeSetId() != $rapnetProductsBlock->getAttributeId()) : ?>
                <div class="details-main-title">
                    <h3 class="title"><?php echo __("Product Details"); ?></h3>
                </div>
                <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <?php if(($label!= 'Overview') && ($label!= 'Certificate')){ ?>
                            <div class="data item title"
                                 aria-labeledby="tab-label-<?= /* @escapeNotVerified */
                                 $alias ?>-title"
                                 data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
                            $alias ?>">
                                <a class="data switch"
                                   tabindex="-1"
                                   data-toggle="switch"
                                   href="#<?= /* @escapeNotVerified */
                                   $alias ?>"
                                   id="tab-label-<?= /* @escapeNotVerified */
                                   $alias ?>-title">
                                    <?= /* @escapeNotVerified */
                                    $label ?>
                                </a>
                            </div>
                            <div class="data item content" id="<?= /* @escapeNotVerified */
                            $alias ?>" data-role="content">
                                <?= /* @escapeNotVerified */
                                $html ?>
                            </div>
                        <?php } ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>


            <!-- rapnet product start -->
            <?php if ($currentProduct->getAttributeSetId() == $rapnetProductsBlock->getAttributeId()) : ?>
                <div class="details-main-title">
                    <h3 class="title"><?php echo __("Product Details"); ?></h3>
                </div>
                <div class="product data items rapnet-pro-page" data-mage-init='{"tabs":{"openedState":"active"}}'>
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <div class="data item title"
                             aria-labeledby="tab-label-<?= /* @escapeNotVerified */
                             $alias ?>-title"
                             data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
                        $alias ?>">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?= /* @escapeNotVerified */
                               $alias ?>"
                               id="tab-label-<?= /* @escapeNotVerified */
                               $alias ?>-title">
                                <?= /* @escapeNotVerified */
                                ($label === 'Product Details')? 'More Details':$label ?>
                            </a>
                        </div>
                        <?php if($label === "Certificate"): ?>
                            <div class="data item content certificate-tab" id="<?= /* @escapeNotVerified */
                            $alias ?>" data-role="content">
                                <div class="certificate-role-rapnet">
                                    <div class="cert-col-right">
                                        <div class="cert-img-main">
                                            <?php if ($currentProduct->getRapnetDiamondLab() == "IGI") : ?>
                                                <a class="cert-hover"
                                                   href='http://www.igiworldwide.com/verify.php?r=<?= $currentProduct->getRapnetDiamondCertimg() ?>'
                                                   target="_blank">
                                                    <img src="<?php echo $block->getViewFileUrl('images/IGI_CERTIFICATE.png'); ?>"
                                                         alt="certificate" title="certificate"/>
                                                </a>
                                            <?php elseif ($currentProduct->getRapnetDiamondLab() == "HRD") : ?>
                                                <a class="cert-hover"
                                                   href='https://my.hrdantwerp.com/?record_number=<?= $currentProduct->getRapnetDiamondCertimg() ?>'
                                                   target="_blank"><img src="<?php echo $block->getViewFileUrl('images/hrd_certificate.png'); ?>"
                                                                        alt="certificate" title="certificate"/>
                                                </a>
                                            <?php else : ?>
                                                <a class="cert-hover"
                                                   href='http://www.diamondselections.com/GetCertificate.aspx?diamondid=<?= $currentProduct->getSku() ?>'
                                                   target="_blank">
                                                    <img src="<?php echo $block->getViewFileUrl('images/certificate-details.png'); ?>"
                                                         alt="certificate" title="certificate"/>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="cert-col-left">
                                        <ul class="items-main">
                                            <li class="item">
                                                <?php echo __("All our Gold Jewellery is Hallmarked by the Bureau of Indian Standards"); ?>
                                                (<?php echo __("BIS"); ?>)
                                            </li>
                                            <li class="item">
                                                <?php echo __("All our Solitaires are Certified by reputed Laboratories like "); ?>
                                                (<?php echo __("GIA, HRD, IGI."); ?>)
                                            </li>
                                            <li class="item">
                                                <?php echo __("All Diamond and Gemstone used in our Jewellery are natural and are accompanied by a Certificate from reputed Laboratories like "); ?>
                                                <?php echo __("SGL, GSL and IGI"); ?>
                                            </li>
                                        </ul>
                                    </div>

                                </div>
                            </div>

                        <?php else:?>
                            <div class="data item content" id="<?= /* @escapeNotVerified */
                            $alias ?>" data-role="content">
                                <?= /* @escapeNotVerified */
                                $html ?>
                            </div>
                        <?php endif;?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <!-- rapnet product end -->
        </div>
    <?php endif; ?>
<?php endif; ?>

<script>
    // require(['jquery', 'jquery/ui'], function ($) {
    //     $(document).ready(function () {
    //         $("#custom-tab-main").tabs();
    //     });
    // });
</script>