<?php
/**
 * @var $block \Codilar\Appointment\Block\AppointmentData
 */
$countryList=$block->getCountriesData();
$regionList=$block->getRegionData();
$countries=$block->getRegionsOfCountry();
?>
<form class="form videostore-form" id="video_appoint_form" name='form' action="<?= $block->getUrl('appointment/videostore/result') ?>"
      data-mage-init='{"validation":{}}' enctype="multipart/form-data" method="POST">
    <?= $block->getBlockHtml('formkey') ?>
    <input type="hidden" value="" name="sku" />
    <div class="form-inputs-main-box">
        <div class="time-slot-main fieldset-main">
            <p class="fieldset-label">Time Slot</p>
            <div class="field datepicker-main">
                <label class="label" for="date"><span><?php  echo __('Pick a date*') ?></span></label>
                <div class="control">
                    <input name="date" autocomplete="off" id="datepicker" class="datepicker only-for-desktop" placeholder="DD | MM | YYYY" value="" type="text" required>
                    <input autocomplete="off" class="datepicker mobile-date-picker only-for-mobile" placeholder="DD | MM | YYYY" value="" type="date" required>
                </div>
            </div>
            <div class="field timeslot-main">
                <label class="label" for="time"><span><?php  echo __('Pick a time slot*') ?></span></label>
                <div class="control">
                    <input name="time" autocomplete="off" id="datetimepicker" class="datepicker only-for-desktop" placeholder="As per your standard time" value="" type="text" required>      
                    <input autocomplete="off" class="datepicker mobile-timepicker only-for-mobile" placeholder="As per your standard time" value="" type="time" required>      
                </div>
            </div>
            <div class="field country-main">
                <label class="label" for="country"><span><?php  echo __('Tell us where you are*') ?></span></label>
                <div class="control">
                    <select class="country-dropdown-video" name="country" required>
                        <option disabled selected>Select your country</option>
                    </select>
                </div>
            </div>
            <div class="field regionlist">
                <label class="label" for="region"><span><?php  echo __(' ') ?></span></label>
                <div class="control">
                    <select class="state-dropdown-video" name="state" required>
                        <option disabled selected>Select your state</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="details-main fieldset-main">
            <p class="fieldset-label">Your Details</p>
            <div class="field name">
                <label class="label" for="name"><span><?php  echo __('Your Name*') ?></span></label>
                <div class="control">
                    <input placeholder="Enter Your Name" type="text" name="name" required/>
                </div>
            </div>
            <div class="field mobile">
                <label class="label" for="mobile"><span><?php  echo __('Phone Number*') ?></span></label>
                <div class="control">
                    <input placeholder="Will call you on this number" minlength="5" maxlength="20" type="number" name="mobile" required/>
                </div>
            </div>
            <div class="field email">
                <label class="label" for="email"><span><?php  echo __('Email') ?></span></label>
                <div class="control">
                    <input placeholder="We’ll send you confirmation and notifications" type="email" name="email"/>
                </div>
            </div>
        </div>

        <div class="extra-main fieldset-main">
            <p class="fieldset-label">Notes for Us</p>
            <div class="field notes">
                <div class="control">
                    <textarea id="note-for-us" name="note-for-us" placeholder="Tell us about the occasion you are shopping for, or which jewellery you’d like to see first, or if you want to see jewellery within a specific price range."></textarea>
                </div>
            </div>
        </div>
    </div>
    <div class="appointment-form-msg-main alert alert-success mt-20 hide">
        <strong>Thank You!</strong> Your submission has been received. Our team executive will get back to you shortly.
    </div>
    <div class="action-button">
        <button type="submit" class="form-button">Submit</button>
    </div>
</form>
<script type="text/javascript">
    require([
        'jquery',
        'mage/calendar'
    ], function ($) {
        $(document).ready(function () {
            var countryList = <?= json_encode($countries); ?>;
            var countryDropdownContainer = $('.country-dropdown-video');
            var stateDropdownContainer = $('.state-dropdown-video');
            var createCountryDropdown = function() {
                countryList.forEach(function(e){
                    countryDropdownContainer.append('<option value="'+e.country[0]+'">'+e.country[0]+'</option>');
                })
                countryDropdownContainer.append('<option value="other">Other</option>');
            }

            var createStateDropdown = function(state) {
                stateDropdownContainer.html('<option disabled selected>Select your state</option>')
                state.forEach(function(el){
                    stateDropdownContainer.append('<option value="'+el+'">'+el+'</option>');
                })
            }
            
            $('.country-dropdown-video').change(function(e){
                var selectedCountryVal = $(this).val();
                if(selectedCountryVal == 'other') {
                    $('.field.regionlist').hide();
                } else {
                    $('.field.regionlist').show();
                    countryList.forEach(function(e){
                        if(e.country[0] == selectedCountryVal) {
                            createStateDropdown(e.state[0]);
                        }
                    })
                }
            })
            createCountryDropdown();
            $('#datepicker').datepicker({
                    dateFormat : "dd-mm-yy",
                    timeFormat : "H:m:s",
                    changeMonth: true,
                    changeYear :true,
                    numberOfMonths: 1,
                    showsTime: true,
                }
            );
            $('#datetimepicker').datetimepicker({
                    timeFormat: "hh:m TT",
                    showsDate: false,
                    showsTime: true,
                    timeOnly: true,
                    controlType: 'select',
                    oneLine: true,
                }
            );
            var form = $('#video_appoint_form');
            form.submit(function (e) {
                if(form.valid()) {
                    e.preventDefault();
                    $('body').loader('show');
                    var city = $('#video_appoint_form .state-dropdown-video').val();
                    var country = $('#video_appoint_form .country-dropdown-video').val();
                    var appointmentDate = $("#video_appoint_form input[name='date']").val();
                    var timeSlot = $("#video_appoint_form #datetimepicker").val();
                    var name = $("#video_appoint_form input[name='name']").val();
                    var mobile = $("#video_appoint_form input[name='mobile']").val();
                    var email = $("#video_appoint_form input[name='email']").val();
                    var note = $("#video_appoint_form #note-for-us").val();
                    var fromkey = $("#video_appoint_form input[name='form_key']").val();
                    var requestUrl = window.location.href;
                    var videostoreRequestStatus ="Yes";
                    var appointmentRequestStatus ="No";
                    if($("#video_appoint_form input[name='sku']").val()) {
                        var sku = $("#video_appoint_form input[name='sku']").val();
                    } else {
                        var sku = '';
                    }
                    var url = "<?= $block->getUrl('appointment/videostore/result') ?>";
                    try {
                        $.ajax({
                            url: url,
                            type: "POST",
                            data: {
                                form_key:fromkey,
                                appointmentDate: appointmentDate,
                                timeSlot: timeSlot,
                                country: country,
                                city: city,
                                name: name,
                                mobile: mobile,
                                email: email,
                                note: note,
                                sku: sku,
                                requestUrl : requestUrl,
                                videostoreRequestStatus:videostoreRequestStatus,
                                appointmentRequestStatus:appointmentRequestStatus
                            },
                            success: function (data) {
                                jQuery('#video_appoint_form').trigger("reset");
                                jQuery('body').loader('hide');    
                                $('.appointment-form-msg-main').removeClass('hide');
                                setTimeout(function(){
                                    $('.appointment-form-msg-main').addClass('hide');
                                },3000);
                            }
                        });
                    }catch (e) {
                    }
                    return false;
                }
            });

            $('.mobile-date-picker').change(function(){
                var selectedDate = $(this).val();
                $('#datepicker').val(selectedDate);
            });
            $('.mobile-timepicker').change(function(){
                var selectedTime = $(this).val();
                $('#datetimepicker').val(selectedTime);
            });
        });
    });
</script>
