<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
/**
 * @var $_helper \Magento\Catalog\Helper\Output
 */
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="attribute-option-main additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
<!--            <caption class="table-caption">--><?//= /* @escapeNotVerified */
//                __('Product Details') ?><!--</caption>-->
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <?php if(($_data['label']!= "SKU") && ($_data['label']!= "Shape") && ($_data['label']!= "Polish") && ($_data['label']!= "Symmetry") && ($_data['label']!= "Measurements") && ($_data['label']!= "Fluorescence") && ($_data['label']!= "Lab") && ($_data['label']!= "Depth")): ?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml(__($_data['label'])) ?></th>
                    <td class="col data"
                        data-th="<?= $block->escapeHtml(__($_data['label'])) ?>"><?= /* @escapeNotVerified */
                        $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
            <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>