<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Telephone $block */
?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('telephone')
            );
        ?>
        <input type="text"
               name="telephone"
               id="telephone"
               minlength="10"
               maxlength="10"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $('#telephone').on('keypress', function(evt) {
                var charCode = (evt.which) ? evt.which : event.keyCode;
                return !(charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57));
            });
        });
    });
</script>
