<?php
/** @var \Codilar\DynamicForm\Block\Form\Renderer\Date $block */
$element = $block->getElement();
$id = $block->getElementId();
$value = $block->getValue();
?>
<div class="form-control element element-type-<?php echo $element->getIdentifier() ?>">
    <label for="<?php echo $id ?>" class="label"><?php echo $element->getLabel() ?></label>
    <div class="control">
        <input data-validate='<?php echo $block->getValidationString() ?>' value="<?php echo $value ?>" data-element_type="<?php echo $element->getType() ?>" type="text" name="<?php echo $element->getName() ?>" id="<?php echo $id ?>" class="<?php echo $element->getClassName() ?>" autocomplete="off" />
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'mage/calendar'], function ($) {
        $('#<?php echo $id ?>').calendar({
            buttonText:"<?php echo __('Select Date') ?>",
            changeYear: true,
            yearRange: "1970:<?php echo date('Y') ?>",
            showAnim: "puff"
        });
    });
</script>
