<?php
/** @var \Codilar\DynamicForm\Block\Form\Renderer\Radio $block */
$element = $block->getElement();
$id = $block->getElementId();
$value = $block->getValue();
?>
<div class="form-control element element-type-<?php echo $element->getIdentifier() ?>">
    <label for="<?php echo $id ?>" class="label"><?php echo $element->getLabel() ?></label>
    <div class="radio-group" id="<?php echo $id ?>">
        <?php foreach ($element->getOptions() as $option): ?>
            <div class="radio-element">
                <label for="<?php echo $id . $option->getValue() ?>" class="label"><?php echo $option->getLabel() ?></label>
                <div class="control">
                    <input data-validate='<?php echo $block->getValidationString() ?>' value="<?php echo $option->getValue() ?>" data-element_type="<?php echo $element->getType() ?>" type="<?php echo 'radio' ?>" name="<?php echo $element->getName() ?>" id="<?php echo $id . $option->getValue() ?>" class="<?php echo $element->getClassName() ?>" <?php echo $value == $option->getValue() ? 'checked' : '' ?> />
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
