<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php

$productId = $this->getRequest()->getParam('product');

if ($productId) :
    $product = $this->getProductById($productId);
    ?>
    <h1 style="text-align: center"><?= $product->getName(); ?><?= __(' can be found at the following stores:&nbsp;')?></h1>
    <hr>
<?php endif; ?>
<div id="amasty_locator_block" style="<?= $block->getMainBlockStyles(); ?>">
    <?php if ($block->getWidgetDescription()) : ?>
        <div>
            <strong><span><?= $block->getWidgetDescription(); ?></span></strong>
        </div>
    <?php endif; ?>
    <div id="amasty_locator_filter">
        <div class="column_right">
            <?php if (!$block->isWidget()) : ?>
                <div class="block-title">
<!--                    <strong><span>--><?//= __('Filter')?><!--</span></strong>-->
                </div>
                <div class="block-content">
                    <?php $attributes = $block->getAttributes();?>
                    <form id="attribute-form" class="attributes" action="#">
                                <div class="store-buttons">
                                <?php foreach ($attributes as $attribute) : ?>
                        <div class="storeclass">
                                    <?php if($attribute['label'] == "Show Rooms"): ?>
                                    <!--<div class="store-button">-->
                                        <button id ="button-label-customer" class="store-button active" onclick="myFunction()">
                                            <div class="customer-attribute-label"><?= $attribute['label'];?>
                                        </button>
                                        <!--</div>-->
                                        <?php elseif ($attribute['label'] == "Customer Service Center"): ?>
                                        <button id ="button-label-1" class="store-button"  onclick="myFunction1()">
                                            <div class="attribute-label"><?= $attribute['label'];?></div>
                                        </button>

                                    <?php endif;?>
                        </div>
                                <?php endforeach;?>

                                </div>
                                <?php foreach ($attributes as $attribute) : ?>
                                    <div class="test-<?= $attribute['attribute_id'];?>">
                                        <input type="hidden" value="<?= $attribute['attribute_id'];?>" name="attribute_id[]">

                                        <div id="limiter-custom_<?= $attribute['attribute_id'];?>" class="limiter-options-custom" <?php if ($attribute['label'] == "Show Rooms"): ?>style="display:block;"<?php else :?>style="display:none"<?php endif;?> >
                                            <?php foreach ($attribute['options'] as $valueId => $option) : ?>
                                                <div class ="limiter-custom-main">
                                                    <div class="limiter-option-custom_<?= $attribute['attribute_id'];?>" data-value="<?=$valueId ?>"<?= $option; ?>
                                                         id="limiter-option-selected">
                                                        <p><?= /* @escapeNotVerified */ $option ?></p>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                        <div class="input-box" id="select-box" style="display:none">
                                            <select id="limiter_<?= $attribute['attribute_id'];?>" data-role="limiter_<?= $attribute['attribute_id'];?>" class="limiter-options" style="display:none" name="option[<?= $attribute['attribute_id'];?>]" <?php if ($attribute['frontend_input'] == 'multiselect'): ?>multiple="multiple"<?php endif;?>>
                                                <?php foreach ($attribute['options'] as $valueId => $option) : ?>
                                                    <option value="<?= $valueId ?>"><?= $option; ?></option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                    </div>


                        <?php endforeach;?>
                    </form>



        </div>




            <?php endif; ?>

        </div>






        <?php if ($block->getShowSearch()) : ?>
            <div class="column_left">
                <div class="block-title">
                    <strong><span><?= __('Search')?></span></strong>
                </div>
                <div class="block-content">

                    <div id="current-address" class="amlocator_input">
                        <label for="address"><?= __('Current Location')?></label>
                        <div class="input-box">
                            <input type="text" value="" class="input-text" id="<?= $block->getSearchId(); ?>"
                                   name="address" placeholder="<?= __('Enter a location')?>" autocomplete="off">
                        </div>
                    </div>
                    <div class="amlocator_input">
                        <label for="radius"><?= __('Search Radius')?></label>
                        <div class="input-box">
                            <select title="" class="select" id="<?= $block->getSearchRadiusId(); ?>" name="radius" >
                                <?php foreach ($block->getSearchRadius() as $range) : ?>
                                    <option value="<?= is_numeric($range) ? $range : ''; ?>"><?= $range ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <?php if ($this->getDistanceConfig()) : ?>
                        <div class="amlocator_input">
                            <label for="measurement"><?= __('Search Radius Measurement')?></label>
                            <div class="input-box">
                                <select title="" class="select" id="amlocator-measurement" name="measurement">
                                    <option value="km"><?= __('km')?></option>
                                    <option selected="selected" value="mi"><?= __('mi')?></option>
                                </select>
                            </div>
                        </div>
                    <?php endif ?>

                    <div class="amlocator_input">
                        <button class="button" title="Filter" id="<?= $block->getSearchButtonId(); ?>">
                        <span>
                            <span>
                                <?= __('Search')?>
                            </span>
                        </span>
                        </button>

                        <button id="locateNearBy" class="button" title="Sort" type="button">
                        <span>
                            <span><?= __('Locate Nearby')?></span>
                        </span>
                        </button>
                    </div>

                    <input type="hidden" id="am_lat" >
                    <input type="hidden" id="am_lng" >
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="amlocator_center">
        <div class="amlocator_mapblock" style="<?= $block->getMapStyles(); ?>">
            <div class="amlocator-map-canvas" id="<?= $block->getMapId(); ?>"></div>
        </div>
        <?php if ($block->getShowLocations()) : ?>
            <div class="amlocator_store_list">
                <?= $block->getLeftBlockHtml(); ?>
            </div>
        <?php endif; ?>
    </div>
</div>


<script type="text/javascript">
    require(['jquery'], function ($) {

        myFunction = function() {
            var x = document.getElementById("limiter-custom_1");
            var y = document.getElementById("limiter-custom_2");

            if (x.style.display === "none") {
                x.style.display = "block";
                y.style.display = "none";
                $('#limiter-custom_1 .limiter-custom-main:first-child .limiter-option-custom_1').click();
                $('body').removeClass('customer-service-tab-selected');                
            }

        }

        myFunction1 = function() {
            var y = document.getElementById("limiter-custom_2");
            var x = document.getElementById("limiter-custom_1");
            var color = document.getElementById("button-label-customer");
            color.style.backgroundColor ="white";
            color.style.color ="black";
            if (y.style.display === "none") {

                y.style.display = "block";
                x.style.display = "none";
                $('#limiter-custom_2 .limiter-custom-main:first-child .limiter-option-custom_2').click();
                $('body').addClass('customer-service-tab-selected');
            }

        }
        $('.limiter-option-custom_1').click(function(data){
            $('#limiter_1').val($(this).attr('data-value')).change();
        });

            $('.limiter-option-custom_2').click(function(data){
                $('#limiter_2').val($(this).attr('data-value')).change();
            });
        $('.store-button').click(function(e) {
            e.preventDefault();
            $('.store-button').removeClass('active');
            /* $('.limiter-option-custom_1').removeClass('active');
            $('.limiter-option-custom_2').removeClass('active'); */
            $(this).addClass('active');
        });
        $('.limiter-option-custom_1').click(function(e) {
            e.preventDefault();
            $('.limiter-option-custom_1').removeClass('active');
            $(this).addClass('active');
        });
        $('.limiter-option-custom_2').click(function(e) {
            e.preventDefault();
            $('.limiter-option-custom_2').removeClass('active');
            $('.limiter-option-custom_1').removeClass('active');
            $(this).addClass('active');
        });

    });


</script>
<script>
    var baloonTemplate = <?= $block->getBaloonTemplate() ?>;
    var amMediaUrl = "<?= $block->getAmStoreMediaUrl() ?>";
    var mapZoom = <?= $block->getMapZoom() ?>;
    var productId = "<?= $block->getProductId() ?>";
    var categoryId = "<?= $block->getCategoryId() ?>";
    var locatorPageUrl = "<?= $this->getLinkToMap(); ?>";
    var widgetLinkText = "<?= $this->getWidgetLinkText(); ?>";
</script>

<script>
    require([
        'jquery',
        'Amasty_Storelocator/js/main',
        'Amasty_Storelocator/js/cluster',
        'domReady!',
        'https://maps.googleapis.com/maps/api/js?sensor=true&libraries=places<?= $block->getApiKey(); ?>'
    ], function ($) {
        var mapId = "#" + "<?= $block->getMapId(); ?>";
        $(mapId).amLocator({
            ajaxCallUrl: "<?= $this->getUrl('amlocator/index/ajax') . $this->getQueryString() ?>",
            useGeo: "<?= $this->getGeoUse()?>",
            jsonLocations: <?= $this->getJsonLocations() ?>,
            imageLocations: "<?= $block->getViewFileUrl('Amasty_Storelocator::images/'); ?>",
            filterAttributeUrl: "<?= $this->getUrl('amlocator/index/attribute') ?>",
            searchButtonId: "<?= $block->getSearchButtonId(); ?>",
            searchRadiusId: "<?= $block->getSearchRadiusId(); ?>",
            searchId: "<?= $block->getSearchId(); ?>",
            storeListId : "<?= $block->getStoresListId(); ?>",
            mapId: "<?= $block->getMapId(); ?>",
            showSearch: <?= $block->getShowSearch(); ?>,
            activeLocation: "<?= $this->getRequest()->getParam('locationId'); ?>"
        });
        $(document).ready(function(){
            $('#limiter-custom_1 .limiter-custom-main:first-child .limiter-option-custom_1').click();
            setTimeout(() => {
                $('.amlocator_center .amlocator_store_list').css('display','block');
               }, 2000);
        });
    });
</script>
