<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php 
/** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php

$productId = $this->getRequest()->getParam('product');

if ($productId) :
    $product = $this->getProductById($productId);
?>
<h1 style="text-align: center">
    <?= $product->getName(); ?>
    <?= __(' can be found at the following stores:&nbsp;') ?>
</h1>
<hr>
<?php endif; ?>
<div class="store-header">
    <!-- <img src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl(); ?>wysiwyg/bushwacker/find_dealer.jpg" /> -->
    <div class="store-title">
        <h1>
            <?= $block->escapeHtmlAttr(__('Find a dealer')) ?>
        </h1>
    </div>
</div>
<div id="amasty_locator_block" style="<?= $block->getMainBlockStyles(); ?>">
    <?php if ($block->getWidgetDescription()) : ?>
    <div>
        <strong><span>
                <?= $block->getWidgetDescription(); ?></span></strong>
    </div>
    <?php endif; ?>
    <div id="amasty_locator_filter">
        <div class="column_right">
            <?php if (!$block->isWidget()) : ?>
            <div class="block-title">
                <strong><span>
                        <?= __('Filter') ?></span></strong>
            </div>
            <div class="block-content">
                <?php $attributes = $block->getAttributes(); ?>
                    <form id="attribute-form" class="attributes" action="#">
                        <input type="text" name="zipcode">
                        <?php foreach ($attributes as $attribute) : ?>
                        <div class="location-attribute">
                            <div class="attribute-label">
                                <?= $attribute['label']; ?>
                            </div>
                            <input type="hidden" value="<?= $attribute['attribute_id']; ?>" name="attribute_id[]">
                            <div class="input-box">
                                <select name="option[<?= $attribute['attribute_id']; ?>]" <?php if
                                    ($attribute['frontend_input']=='multiselect' ) : ?>multiple="multiple"
                                    <?php endif; ?>>
                                    <option value="">
                                        <?= __('Please Select'); ?>
                                    </option>
                                    <?php foreach ($attribute['options'] as $valueId => $option) : ?>
                                    <option value="<?= $valueId ?>">
                                        <?= $option; ?>
                                    </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </form>

                    <button class="button filter-attribute" title="Filter" id="filterAttribute"><span><span>
                                <?= __('Filter') ?></span></span></button>
            </div>
            <?php endif; ?>
        </div>
        <?php if ($block->getShowSearch()) : ?>
        <div class="column_left">
            <div class="block-title">
                <strong><span>
                        <?= __('Search') ?></span></strong>
            </div>
            <div class="block-content">

                <div id="current-address" class="amlocator_input">
                    <label for="address">
                        <?= __('Current Location') ?></label>
                    <div class="input-box">
                        <input type="text" value="" class="input-text addr-text" id="<?= $block->getSearchId(); ?>"
                            name="address" placeholder="<?= __('Enter city or zip code') ?>" autocomplete="off">
                    </div>
                </div>
                <div class="amlocator_input">
                    <label for="radius">
                        <?= __('Search Radius') ?></label>
                    <div class="input-box">
                        <select title="" class="select" id="<?= $block->getSearchRadiusId(); ?>" name="radius">
                            <option value="" disabled selected hidden>DISTANCE</option>
                            <?php foreach ($block->getSearchRadius() as $range) : ?>
                            <option value="<?= is_numeric($range) ? $range : ''; ?>">
                                <?php if( is_numeric( $range ) && $range!=1 ){

                                    echo  $range." miles";
                                }
                                else if( $range ==1) {

                                    echo  $range." mile";
                                }

                                else {

                                    echo  $range ;
                                }?>
                            </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <?php if ($this->getDistanceConfig()) : ?>
                <div class="amlocator_input">
                    <label for="measurement">
                        <?= __('Search Radius Measurement') ?></label>
                    <div class="input-box">
                        <select title="" class="select" id="amlocator-measurement" name="measurement">
                            <option value="km">
                                <?= __('km') ?>
                            </option>
                            <option selected="selected" value="mi">
                                <?= __('mi') ?>
                            </option>
                        </select>
                    </div>
                </div>
                <?php endif ?>

                <div class="amlocator_input">
                    <button disabled class="button btn-search" title="Filter" id="<?= $block->getSearchButtonId(); ?>">
                        <span>
                            <span>
                                <?= __('FIND A DEALER') ?>
                            </span>
                        </span>
                    </button>

                    <button id="locateNearBy" class="button" title="Sort" type="button">
                        <span>
                            <span>
                                <?= __('Locate Nearby') ?></span>
                        </span>
                    </button>
                </div>

                <input type="hidden" id="am_lat">
                <input type="hidden" id="am_lng">
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="amlocator_center">
        <div class="amlocator_mapblock" style="<?= $block->getMapStyles(); ?>">
            <div class="amlocator-map-canvas" id="<?= $block->getMapId(); ?>"></div>
        </div>
        <?php if ($block->getShowLocations()) : ?>
        <div class="amlocator_store_list" style="<?= $block->getStoreListStyles(); ?>">
            <?= $block->getLeftBlockHtml(); ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
    var baloonTemplate = <?= $block->getBaloonTemplate() ?>;
    var amMediaUrl = "<?= $block->getAmStoreMediaUrl() ?>";
    var mapZoom = <?= $block->getMapZoom() ?>;
    var productId = "<?= $block->getProductId() ?>";
    var categoryId = "<?= $block->getCategoryId() ?>";
    var locatorPageUrl = "<?= $this->getLinkToMap(); ?>";
    var widgetLinkText = "<?= $this->getWidgetLinkText(); ?>";
</script>

<script>
    require([
        'jquery',
        'Amasty_Storelocator/js/main',
        'Amasty_Storelocator/js/cluster',
        'domReady!',
        'https://maps.googleapis.com/maps/api/js?sensor=true&libraries=places<?= $block->getApiKey(); ?>'
    ], function ($) {
        var mapId = "#" + "<?= $block->getMapId(); ?>";
        $(mapId).amLocator({
            ajaxCallUrl: "<?= $this->getUrl('amlocator/index/ajax') . $this->getQueryString() ?>",
            useGeo: "<?= $this->getGeoUse() ?>",
            jsonLocations: <?= $this->getJsonLocations() ?>,
            imageLocations: "<?= $block->getViewFileUrl('Amasty_Storelocator::images/'); ?>",
            filterAttributeUrl: "<?= $this->getUrl('amlocator/index/attribute') ?>",
            searchButtonId: "<?= $block->getSearchButtonId(); ?>",
            searchRadiusId: "<?= $block->getSearchRadiusId(); ?>",
            searchId: "<?= $block->getSearchId(); ?>",
            storeListId: "<?= $block->getStoresListId(); ?>",
            mapId: "<?= $block->getMapId(); ?>",
            showSearch: <?= $block->getShowSearch(); ?>,
            activeLocation: "<?= $this->getRequest()->getParam('locationId'); ?>"
        });
        $('.addr-text').on("input", function () {
            if (this.value) {
                $('.amlocator_input .btn-search').prop("disabled", false);
            } else {
                $('.amlocator_input .btn-search').prop("disabled", true);
            }
        });
    });
</script>