<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
$index = 1;
?>
<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php
$locations = $block->getLocations();

$currentDate = $block->timezoneInterface->date();
$currentDay = strtolower($block->timezoneInterface->convertConfigTimeToUtc($currentDate, 'l'));
$dayNames = $block->dataHelper->getDaysNames();
?>
<div id="getStoresListId">
    <?php if(!empty ($locations)) { ?>
    <?php foreach ($locations as $location) : ?>
    <span name="leftLocation" data-mapid="<?= $block->getMapId(); ?>" data-amid="<?= $location->getId(); ?>">
            <div class="location_header"> <?= "$index. "; ?><?= $this->escapeHtml($location->getName()); ?></div>
            <strong><a class="telephone" href="tel:<?= $this->escapeHtml($location->getPhone()); ?>">T: <?= $this->escapeHtml($location->getPhone()); ?> </a></strong>
            <br><br>
            <div class="store-address-main">
                <p class="store-address"><?= $this->escapeHtml($location->getAddress()); ?><br>
                <?= $this->escapeHtml($location->getCity()); ?> <?= $this->escapeHtml($location->getState()); ?>, <?= $this->escapeHtml($location->getZip()); ?>
                    <strong><a class="co-google-maps-link" href="https://maps.google.com/?saddr=your+location&daddr=<?= $this->escapeHtml($location->getLat()); ?>,<?= $this->escapeHtml($location->getLng()); ?>" target="_blank">Directions &gt;</a></strong>
                 </p>
             </div>

         </span>
            <?php $index++; ?>
        <?php endforeach; ?>
           <?php }
     else
     {
         echo "No Dealers Meet Your Search Criteria";
  }?>
