<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $blockObj \Codilar\Base\Block\Common
 */
$blockObj= $block->getLayout()->createBlock('Codilar\Base\Block\Common');

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<p class="toolbar-amount" id="toolbar-amount">
<span class="category-title"><?= __($blockObj->getCategoryName()); ?></span>
    <?php if ($block->getTotalNum() == 1): ?>
        <?php /* @escapeNotVerified */ echo __('%1 Item',
           '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php else: ?>
        <?php /* @escapeNotVerified */ echo __('%1 Items',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php endif; ?>
</p>
