<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
              data-mage-init='{
                "validation":{}
            }'
        >
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <div class="control">
                        <input name="login[username]"
                               value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?>
                            autocomplete="off"<?php endif; ?>
                               id="emailmobile"
                               type="text"
                               class="input-text"
                               placeholder="<?= $block->escapeHtml(__('Email/Mobile Number *')) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}'
                               >
                    </div>
                    <div class="generate-otp"><span class="login-generate-otp"><?= $block->escapeHtml(__('Generate OTP')) ?></span></div>
                    <div class="resend-otp"><span class="login-resend-otp"><?= $block->escapeHtml(__('Resend OTP')) ?></span></div>
                    <div class="otp_sent"><span><?= $block->escapeHtml(__('OTP Sent')) ?></span></div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" 
                        placeholder="<?= $block->escapeHtml(__('Password/OTP *')) ?>"
                        type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password/OTP')) ?>">
                    </div>
                </div>
                <div class="login-error-message"></div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary submit-button" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="primary"><button type="submit" class="action login primary mobile-otp-button" name="mobile-otp-button" id="otp-button"><span><?= $block->escapeHtml(__('Sign In Using OTP')) ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span class="forgot-password-link"><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($,alert) {
        $('#login-form').submit(function(event) {
            const pageMessage = $(".page .messages");
            pageMessage.remove();
            const errorMessage = $(".login-error-message");
            const otpErrorMessage = $(".otp_sent");
            errorMessage.hide();
            otpErrorMessage.hide();
            var emailpattern = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i;
            var mobilepattern = /^(\+\d{1,3}[- ]?)?\d{7,15}$/;
            var inputval =$('#emailmobile').val();
            if(inputval == '' && $('#pass').val()=='') {
                $('#emailmobile').focus();
                otpErrorMessage.text("Enter Email/Mobile Number.");
                otpErrorMessage.show();
                errorMessage.text("Enter Password.");
                errorMessage.show();
                return false;
            }
            else if(inputval == '' || inputval == null) {
                $('#emailmobile').focus();
                otpErrorMessage.text("Enter Email/Mobile Number.");
                otpErrorMessage.show();
                return false;
            }
            else if(!emailpattern.test(inputval) && !mobilepattern.test(inputval)){
                otpErrorMessage.text("Invalid Username. Try with Mobile Number or Email Id.");
                otpErrorMessage.show();
                return false;
            }
            else if($('#pass').val()=='' || $('#pass').val()==null ){
                $('#pass').focus();
                errorMessage.text("Enter Password.");
                errorMessage.show();
                return false;

            }
        });
        jQuery(document).ready( function() {
            const errorMessage = $(".login-error-message");
            var generateOtp = $('.generate-otp');
            var otpButton = $('.mobile-otp-button');
            var resendButton = $(".resend-otp");
            otpButton.prop('disabled', true);
            generateOtp.on('click',function(){
                sendOtp();
            });
            resendButton.on('click',function(){
                sendOtp();
            });
            otpButton.on('click',function(){
                var phoneNumber = $("#pass").val();
                if(phoneNumber.length !== 6){
                    errorMessage.text("OTP Should be six digits.");
                    errorMessage.show();
                    return false;
                }
                $('#login-form').submit();
            });
        });
        function sendOtp() {
            const pageMessage = $(".page .messages");
            pageMessage.remove();
            var generateOtp = $('.generate-otp');
            var otpButton = $('.mobile-otp-button');
            const errorMessage = $(".login-error-message");
            const otpErrorMessage = $(".otp_sent");
            var resendButton = $(".resend-otp");
            otpButton.prop('disabled', true);
            errorMessage.hide();
            otpErrorMessage.hide();
            var mobilepattern = /^(\+\d{1,3}[- ]?)?\d{7,15}$/;
            var otpLoginUrl = "<?php echo $block->getUrl('customer/otp/generateotp') ?>";
            var phoneNumber = $("#emailmobile").val();
            if(!$.isNumeric(phoneNumber)){
                otpErrorMessage.text("Enter valid Mobile Number.");
                otpErrorMessage.show();
                return false;
            }
            else if(phoneNumber.length < 1){
                otpErrorMessage.text("Enter Mobile number.");
                otpErrorMessage.show();
                return false;
            }
            else if(!mobilepattern.test(phoneNumber)){
                otpErrorMessage.text("Please enter at least 10 characters.");
                otpErrorMessage.show();
                return false;
            }
            $.ajax(otpLoginUrl, {
                method: "POST",
                data: {
                    phone_number:phoneNumber
                },
                showLoader: true,
                success: function(response){
                    if(response.status == false){
                        otpErrorMessage.text(response.message);
                        otpErrorMessage.css('color',"#e02b27");
                        generateOtp.show();
                        resendButton.hide();
                    }
                    else{
                        otpErrorMessage.text(response.message);
                        otpErrorMessage.css('color',"#008000");
                        otpButton.prop('disabled', false);
                        generateOtp.hide();
                        resendButton.hide();
                        setTimeout(function(){
                            resendButton.show();
                        },60000);
                    }
                    otpErrorMessage.show();
                },
                error: function (e) {

                }
            });
        }
    });
</script>