<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue): ?>
    <div class="product attribute <?= /* @escapeNotVerified */ $_className ?>">
        <?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */ $_attributeLabel ?></strong><?php endif; ?>
        <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>>
            <?= /* @escapeNotVerified */ $_attributeValue ?>
            <?php
            if ($_product->getResource()->getAttribute('prop65')->getFrontend()->getValue($_product)!="No"): ?>



                <?php if($_className == 'description') { ?>

                    <div class="message notice">

                        <div>
                            <p>
                                Prop 65 Warning: Cancer and Reproductive Harm, for more information go to
                                <a href="https://www.p65warnings.ca.gov/" target="_blank">www.p65warnings.ca.gov</a>
                            </p>
                        </div>
                    </div>
                <?php }?>
            <?php endif ?>


        </div>
    </div>
<?php endif; ?>