<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <div class="only-for-mobile scroll-to-right">
            <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </div>
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function($) {
        if($(window).width() < 767) {
            $('.scroll-to-right').click(function(){
                $('.product.info.detailed .product.data.items').animate({
                scrollLeft: "+=250px"
                }, "slow");
            });
            
            $('.product.info.detailed .product.data.items .title').click(function(){
                var height = $(this).next('.content').innerHeight();
                if($(this).attr('id') == 'tab-label-reviews') {
                    $('.product.info.detailed .product.data.items').css('height', 380+'px');
                } else {
                    $('.product.info.detailed .product.data.items').css('height', height+40+'px');
                }
            })

            //observer for tab active
            var tabInitialized = false;
            var observer = new MutationObserver(function(mutations) {
                mutations.forEach(function(mutation) {
                    var hasClass = mutation.target.className.includes('active');
                    if (hasClass && !tabInitialized) {
                        setTimeout(() => {
                            $('.product.info.detailed .product.data.items .title')[0].click();
                        }, 200);
                        tabInitialized = true;
                    }
                });
            });

            var config = {
                attributes: true,
                childList: true,
                characterData: true
            };

            observer.observe(document.getElementsByClassName('title')[0], config);
        }
    });
</script>
